@startuml
autonumber
title       Admin wants to show users
actor       Admin
participant Application
database    Database

ref over Admin, Application, Database: Login
ref over Admin, Application, Database: Show admin

Admin -> Application: GET /admin/
Application -> Database: Get users
Database -> Application: return users
Application -> Admin: Render /admin/ with users

@enduml
