@startuml
autonumber
title       User wants to add an image
actor       User
participant Application
database    Database

ref over User, Application, Database: Login
ref over User, Application, Database: Show user
ref over User, Application, Database: Show images

User -> Application: POST /user/image/new
Application -> Application: Check values
alt values are valid
    Application -> Database: Add image
    Database -> Application: Add image
    Application -> User: Redirect to /user/
else values are invalid
    Application -> Application: Add error
    Application -> User: Render /user/image/new
end

@enduml
